from typing import Literal, TypedDict

from pydantic import BaseModel, Field


class TickerMetrics(BaseModel):
    """Computed metrics for a single ticker (produced by calculate_metrics). Shared by v1 and v2."""

    total_return_pct: float
    annualized_volatility_pct: float


class PortfolioSummary(BaseModel):
    """Structured explanation of portfolio risk/performance, generated by the LLM. v2 only.

    Each field's description below is sent to Gemini as part of the structured-output
    schema (via with_structured_output) — it's the prompt for *this specific field*,
    not just documentation for humans reading the code.
    """

    risk_rating: Literal["low", "moderate", "high"] = Field(
        description="Overall risk level of the portfolio, based on volatility and composition"
    )
    key_drivers: list[str] = Field(
        description="2-4 short bullet points explaining what's driving the risk/performance assessment"
    )
    confidence: Literal["low", "medium", "high"] = Field(
        description=(
            "How confident this assessment is given the available data "
            "(e.g. low confidence with very few tickers or a short price history)"
        )
    )
    explanation: str = Field(
        description=(
            "A short, plain-language paragraph directly answering the user's question, "
            "written for a retail investor with no finance background"
        )
    )


class AgentStateV1(TypedDict):
    """v1 state: fetch_data -> calculate_metrics -> summarize_v1. summary is free-text prose."""

    tickers: list[str]  # input: e.g. ["AAPL", "VWCE.DE"]
    question: str  # input: the user's natural-language question
    price_data: dict[str, list[float]]  # set by fetch_data: ticker -> closing prices
    metrics: dict[str, TickerMetrics]  # set by calculate_metrics: ticker -> return/volatility
    summary: str  # set by summarize_v1: free-text LLM-generated answer


class AgentStateV2(TypedDict):
    """v2 state: fetch_data -> calculate_metrics -> summarize_v2. summary is structured output.

    Identical to AgentStateV1 except for the summary field's type — kept as a separate
    TypedDict (rather than a shared base class with an overridden field) since changing
    a field's type in a TypedDict subclass isn't safely expressible; duplicating the four
    unchanged fields is a small, explicit cost worth paying for that clarity.
    """

    tickers: list[str]
    question: str
    price_data: dict[str, list[float]]
    metrics: dict[str, TickerMetrics]
    summary: PortfolioSummary  # set by summarize_v2: structured LLM-generated answer


# Example of a fully populated v1 state (after all three nodes have run):
#
# example_state_v1: AgentStateV1 = {
#     "tickers": ["AAPL", "VWCE.DE"],
#     "question": "How risky is this portfolio?",
#     "price_data": {
#         "AAPL": [189.50, 190.20, 187.30, 193.10],       # closing prices, oldest -> newest
#         "VWCE.DE": [102.40, 102.80, 101.90, 103.50],
#     },
#     "metrics": {
#         "AAPL": TickerMetrics(total_return_pct=1.9, annualized_volatility_pct=22.4),
#         "VWCE.DE": TickerMetrics(total_return_pct=1.07, annualized_volatility_pct=14.8),
#     },
#     "summary": "Your portfolio shows moderate risk: AAPL is significantly more "
#                "volatile (22.4% annualized) than VWCE.DE (14.8%)...",
# }
#
# Example of a fully populated v2 state — same shape, but "summary" is structured:
#
# example_state_v2: AgentStateV2 = {
#     **example_state_v1,  # tickers, question, price_data, metrics are identical
#     "summary": PortfolioSummary(
#         risk_rating="moderate",
#         key_drivers=[
#             "AAPL is significantly more volatile (22.4%) than VWCE.DE (14.8%)",
#             "VWCE.DE's diversification offsets AAPL's swings somewhat",
#         ],
#         confidence="high",
#         explanation="Your portfolio shows moderate risk: AAPL is significantly more "
#                     "volatile than VWCE.DE...",
#     ),
# }
#
# At the start of a graph run, only "tickers" and "question" are populated;
# the rest fill in progressively as fetch_data -> calculate_metrics -> summarize_vN run.
